spring:
  datasource:
#    url:  jdbc:mysql://127.0.0.1:3306/asakatu
    username: asakatu
    password: himitu
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
    schema: classpath:schema-product.sql

  jpa:
    hibernate:
      ddl-auto: none