spring:
  datasource:
    url:  jdbc:mysql://db:3306/asakatu
    username: asakatu
    password: himitu
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:schema-product.sql

  jpa:
    hibernate:
      ddl-auto: none