spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/asakatu
    username: asakatu
    password: himitu
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:schema-product.sql

  jpa:
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB


cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    stack:
      auto: false
    region:
      auto: false
      static: us-east-1


s3:
  profile:
    bucket: nocox-exp57-public
    folder: asakatu_user_profile
    defaultImage: human-icon-big.png
    region: us-east-1
  reaction:
    bucket: nocox-exp57-public
    folder: asakatu_reaction
