spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/asakatu
    username: asakatu
    password: himitu
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:schema_prod.sql

  jpa:
    hibernate:
      ddl-auto: none